### ISSUE TITLE
I ordered the premium version but didn't get an email with verification code

### ISSUE THREAD

**Issue by MachoMatty** [smoothkeyscroll/issues#1]
I've searched for a contact to send this to but this seems to be the only website I'm getting for support.
My PayPal transaction ID is  

0N896561WY1276349

If someone comes across this and knows how I can get in contact with the developer so that they can just send me a verification code so I can activate it I'd be very grateful if they let me know who to talk to. 
In case the developer(s) do come across this and want to speed things up my email I used to buy it is: 

carrickerm08@gmail.com

(I also know this is a website for collaborating with code but I've no idea where else to submit this 'issue')
Thanks, Matt

**Comment by franciscolourenco** [comment]
Replied. You can find our email address at the bottom of https://www.smoothkeyscroll.com/
