### ISSUE TITLE
Chrome extension conflicting with Event handles

### ISSUE THREAD

**Issue by Saud-97** [smoothkeyscroll/issues#10]
Hello there,

I've noticed many websites that have some type of (custom) js scrolling are not working good with the extension.
Can you add an option to force override the keys and scroll to make them work in all cases even when there are other event handles already in-place?

This is an example, manga website I was having issues with.
[https://iimanga.com/martial-peak-chapter-1770/](https://iimanga.com/martial-peak-chapter-1769/)

**Comment by Saud-97** [comment]
@franciscolourenco

**Comment by franciscolourenco** [comment]
Hi @saud-97, I have not been having time to work on Smooth Key Scroll lately, and can't promise when I will be able to implement this feature.

**Comment by Saud-97** [comment]
@franciscolourenco thank you for the reply. No problems, I am using another extension for now, let me know if you get the time and fix this issue I will be happy to download it again.
