### ISSUE TITLE
Inconsistent behavior when page contains multiple scrollable areas

### ISSUE THREAD

**Issue by maxrothman** [smoothkeyscroll/issues#13]
On certain websites with multiple scrollable areas, Smooth Key Scroll prevents scrolling of all but one of those areas. For example, on https://docs.readthedocs.io/en/stable/tutorial/:

With Smooth Key Scroll disabled, I can focus on the different scrollable areas and scroll them independently:

https://user-images.githubusercontent.com/2607086/212210564-a0a08bdc-b363-4a47-9c53-b92f04861f73.mov

With Smooth Key Scroll enabled, I cannot scroll the main content area:

https://user-images.githubusercontent.com/2607086/212210761-4dc0cc0f-73e9-4454-af3d-80603b950e10.mov

**Comment by franciscolourenco** [comment]
Hi @maxrothman thank you for the report. I'm in the process of fixing this bug. Do you know other websites affected by this?

**Comment by maxrothman** [comment]
I don't think so, this is the only one I've come across.

**Comment by franciscolourenco** [comment]
There are still some improvements to be made on other websites like Youtube, but docs.readthedocs.io/en/stable/tutorial has been fixed now.
