### ISSUE TITLE
Key scrolling (partially) stopped working

### ISSUE THREAD

**Issue by sNw0w** [smoothkeyscroll/issues#14]
Hi,
Key scrolling (partially) stopped working on any keys.
It doesn't scroll at all unless I click some specific place/part of the screen.
Around two weeks ago it worked flawlessly.
If needed I can record some of the behavior.
//Edit// After looking at the latest changelog in the Chrome webstore I believe it's somewhat correlated to change with scrolling different areas. It now feels that after clicking the "scrollable" area it'll work, but otherwise, it won't.
For example on extensions's settings site, after clicking something that's not the central block it works. After clicking central block it doesn't.

**Comment by franciscolourenco** [comment]
@sNw0w thank you for bringing this to my attention, I also received your email 🙏  

A fix will be released as soon as v2.8.5 is approved.
