### ISSUE TITLE
Last update broke it

### ISSUE THREAD

**Issue by TruthAreLies** [smoothkeyscroll/issues#15]
Since no one else seems to be reporting this, I am guessing it's an issue on legacy chrome.

 my Windows 7 laptop. It is running an old Chrome version since Google doesn't want to update for Windows 7 anymore.

but yeh if smootks is on arrow keys do noting and if i turn it on they start working again

**Comment by TruthAreLies** [comment]
If you still have the file, can I have the pre-patch file sent? Preferably something Chrome can't patch.

**Comment by franciscolourenco** [comment]
@TruthAreLies which version of Chrome are you running? Scrolling was broken in v2.8.4, but it should be fixed in v2.8.5 of the extension. Can you confirm that you have this version installed in the extensions panel? Thanks!

**Comment by TruthAreLies** [comment]
I am on v2.8.5 of the extension. It broke 2-3 days ago on Chrome v109.0.5414.120. It won't update further unless I update my laptop to Windows 10, but it's too old to accept the Windows 10 installer.

**Comment by TruthAreLies** [comment]
Never mind, I turned on the extension, and now it works. I must have been on 2.8.4 when it broke, and it now works. Cheers :)
