### ISSUE TITLE
Remove auto-popup installation page

### ISSUE THREAD

**Issue by wasp604** [smoothkeyscroll/issues#5]
Please get rid of auto-popup installation page that plagues chrome store extensions. I log into many computers, and get bombarded with intrusive popups from many extensions being installed, and this one is part of the problem.

**Comment by franciscolourenco** [comment]
@wasp604 I'm not sure what you are referring to. Would you mind sharing a screenshot? Thank you

**Comment by wasp604** [comment]
This page pops up when I install the extension, as is common for chrome
store extensions. Maybe I need an extension that blocks these? I think it
may be too common a thing for me to ask each developer to remove them.
[image: Screen Shot 2018-10-14 at 14.07.02.png]

**Comment by franciscolourenco** [comment]
Think this best solutio would be to open the welcome page only the first time the extension is installed, and then store this information in the user's profile and not open it automatically again.

**Comment by franciscolourenco** [comment]
Fixed in v2.7.1
