### ISSUE TITLE
Is there a way to disable it on Youtube videos?

### ISSUE THREAD

**Issue by florianwalther-private** [smoothkeyscroll/issues#6]
I use the arrow keys to jump back and forth in Youtube videos but the plugin interferes with that. Is there a way to fix that?

**Comment by franciscolourenco** [comment]
Hi @FlorianWalther not at them moment. I will add a way to blacklist websites, and possibly handle youtube better. Which keys do you use the navigate videos?

**Comment by florianwalther-private** [comment]
Thank you for the quick response. I tried it with WASD but the arrow keys are still working for your plugin.

**Comment by florianwalther-private** [comment]
Sorry I misread your question. I use the arrow keys on Youtube (left and right)

**Comment by lobre** [comment]
+1 for a list of configurable websites on which it is not enabled!

**Comment by franciscolourenco** [comment]
Hi guys, I'm about to add an option to blacklist pages. Any pages that you would recommend adding by default?

**Comment by franciscolourenco** [comment]
Blacklist available from v2.8.0
