### ISSUE TITLE
I found that this extension was the culprit for a laggy Chrome browser in battery mode.

### ISSUE THREAD

**Issue by pbakes** [smoothkeyscroll/issues#9]
I was having global problems in the browser with text input lag/latency, as well as scrolling and page loading latency on battery mode, and I finally found that this extension was the problem. Almost as if the browser would freeze up for 25-250ms when doing anything. Disabling the extension fixed the problem.

Using Chrome 94.0.4606.61
Windows 10 Pro 19043.1237
Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz, 32.0 GB RAM

**Comment by franciscolourenco** [comment]
Interesting, you don't even seem to have an underpowered machine. I've never experienced any problem of this sort, but I'm not on Windows. Can you share a reproduction of the problem? Thanks
